### ISSUE TITLE
after selecting the theme, the options are not switched.

### ISSUE THREAD

**Issue by PeixyJ** [cameron-goddard/Minesweeper-Desktop#1]
<img width="591" alt="image" src="https://github.com/cameron-goddard/Minesweeper-Desktop/assets/45998593/fdd389fe-2dd8-47bc-89f7-b8a6b5fe8b93">

**Comment by cameron-goddard** [comment]
Thank you for pointing this out! This has been fixed in the latest commit, and will be released as an update soon.
