### ISSUE TITLE
right click smaple app erro exit;

### ISSUE THREAD

**Issue by PeixyJ** [cameron-goddard/Minesweeper-Desktop#2]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Minesweeper [68466]
Path:                  /Applications/Minesweeper.app/Contents/MacOS/Minesweeper
Identifier:            com.camerongoddard.Minesweeper
Version:               0.1.0 (1)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-28 10:23:51.4905 +0800
OS Version:            macOS 14.3.1 (23D60)
Report Version:        12
Anonymous UUID:        716B7F88-CA2F-82D5-5A3B-B8CC03EDCA93

Sleep/Wake UUID:       C347BB6F-D4BC-4FDE-A415-84F5C93EA231

Time Awake Since Boot: 70000 seconds
Time Since Wake:       5922 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001027652e4

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [68466]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Minesweeper                   	       0x1027652e4 0x10275c000 + 37604
1   Minesweeper                   	       0x10276381c 0x10275c000 + 30748
2   Minesweeper                   	       0x102763e84 0x10275c000 + 32388
3   SpriteKit                     	       0x1f3e59108 -[SKView rightMouseDown:] + 260
4   AppKit                        	       0x187011ea8 _routeRightMouseDownEvent + 256
5   AppKit                        	       0x18660c410 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 400
6   AppKit                        	       0x18660c0ac -[NSWindow(NSEventRouting) sendEvent:] + 284
7   AppKit                        	       0x186ccaf60 -[NSApplication(NSEventRouting) sendEvent:] + 1604
8   AppKit                        	       0x18691b5bc -[NSApplication _handleEvent:] + 60
9   AppKit                        	       0x1864d43a0 -[NSApplication run] + 512
10  AppKit                        	       0x1864ab640 NSApplicationMain + 880
11  Minesweeper                   	       0x102773628 0x10275c000 + 95784
12  dyld                          	       0x1828a50e0 start + 2360

Thread 1:: CVDisplayLink
0   libsystem_kernel.dylib        	       0x182be906c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x182c26628 _pthread_cond_wait + 1272
2   CoreVideo                     	       0x18b603528 CVDisplayLink::waitUntil(unsigned long long) + 328
3   CoreVideo                     	       0x18b6025f4 CVDisplayLink::runIOThread() + 504
4   libsystem_pthread.dylib       	       0x182c26034 _pthread_start + 136
5   libsystem_pthread.dylib       	       0x182c20e3c thread_start + 8

Thread 2:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	       0x182be5874 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x182bf7cf0 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x182bee4b0 mach_msg_overwrite + 476
3   libsystem_kernel.dylib        	       0x182be5bf8 mach_msg + 24
4   CoreFoundation                	       0x182d03b84 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                	       0x182d0244c __CFRunLoopRun + 1208
6   CoreFoundation                	       0x182d0193c CFRunLoopRunSpecific + 608
7   AppKit                        	       0x18660a160 _NSEventThread + 144
8   libsystem_pthread.dylib       	       0x182c26034 _pthread_start + 136
9   libsystem_pthread.dylib       	       0x182c20e3c thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	       0x182c20e28 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x182c20e28 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	       0x182c20e28 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001339cbf58   x1: 0x0000000600000003   x2: 0x000000000000000a   x3: 0x0000000000000000
    x4: 0xf00000000000000b   x5: 0x00000001339cbf50   x6: 0x000000000000000f   x7: 0x00000000000b0007
    x8: 0xfffffffe00000000   x9: 0x0000000600000003  x10: 0x0000000400000003  x11: 0x00000001339cbf7b
   x12: 0x0000000000000000  x13: 0x000000000000004d  x14: 0x0000000008000000  x15: 0x0000000000008421
   x16: 0x00000001928de048  x17: 0x2e3f0001daf855d8  x18: 0x0000000000000000  x19: 0x0000000132710e30
   x20: 0x0000000000000000  x21: 0x00000001339cbf50  x22: 0x0000000000000001  x23: 0x00000001339a5ae0
   x24: 0x00000001339a5ae0  x25: 0x0000000000000110  x26: 0x00000001d9a0b000  x27: 0x0000000000000114
   x28: 0x000000002bd80025   fp: 0x000000016d6a3460   lr: 0x00000001027651e8
    sp: 0x000000016d6a3410   pc: 0x00000001027652e4 cpsr: 0x60001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x102ab4000 -        0x102abffff libobjc-trampolines.dylib (*) <39d1d8d0-6996-3bd4-8ce9-39512bb65c82> /usr/lib/libobjc-trampolines.dylib
       0x102cf8000 -        0x102d3bfff org.sparkle-project.Sparkle (2.6.0-beta.1) <80b1ada3-968b-3708-96c5-3994e66106a7> /Applications/Minesweeper.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x10275c000 -        0x1027abfff com.camerongoddard.Minesweeper (0.1.0) <2823d3cc-2b0a-3964-a291-818874629f07> /Applications/Minesweeper.app/Contents/MacOS/Minesweeper
       0x1f3e38000 -        0x1f3fa3fff com.apple.SpriteKit (1.0) <47d46926-2841-3705-b017-8ebae3987804> /System/Library/Frameworks/SpriteKit.framework/Versions/A/SpriteKit
       0x1864a7000 -        0x1877d2fff com.apple.AppKit (6.9) <873e5da0-bc01-399b-bf60-4066922d6a17> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       0x18289f000 -        0x182933387 dyld (*) <50746901-db0e-39a0-b391-baaa6b82ad0f> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x1924f5000 -        0x192a35fff libswiftCore.dylib (*) <7eba7ef0-57d2-3155-b45d-1a4d40a732f3> /usr/lib/swift/libswiftCore.dylib
       0x182be4000 -        0x182c1efff libsystem_kernel.dylib (*) <a7228b5d-53c7-3fe9-84e4-2a8c04dcf051> /usr/lib/system/libsystem_kernel.dylib
       0x182c1f000 -        0x182c2bff3 libsystem_pthread.dylib (*) <449bbad3-f7ef-371d-9a59-fd4ffa78289b> /usr/lib/system/libsystem_pthread.dylib
       0x18b600000 -        0x18b65dfff com.apple.CoreVideo (1.8) <9cd650ce-26fe-3a73-9855-6b3404235ad5> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
       0x182c86000 -        0x18315dfff com.apple.CoreFoundation (6.9) <6030a572-b731-3f46-b3a0-2598fbb98c9a> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 3
    thread_create: 0
    thread_set_state: 52

VM Region Summary:
ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)
Writable regions: Total=329.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=329.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        1 
Activity Tracing                   256K        1 
CG image                           112K        4 
ColorSync                          560K       26 
CoreAnimation                      912K       55 
CoreGraphics                        48K        3 
CoreUI image data                  944K        6 
Dispatch continuations            80.0M        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           237.6M       50 
MALLOC guard page                  192K       12 
STACK GUARD                       56.1M        6 
Stack                             10.6M        6 
VM_ALLOCATE                        208K       13 
__AUTH                            3072K      423 
__AUTH_CONST                      33.5M      646 
__CTF                               824        1 
__DATA                            17.4M      635 
__DATA_CONST                      32.8M      654 
__DATA_DIRTY                      1953K      235 
__FONT_DATA                          4K        1 
__LINKEDIT                       892.1M        4 
__OBJC_RO                         71.2M        1 
__OBJC_RW                         2171K        1 
__TEXT                           754.0M      675 
dyld private memory                272K        2 
mapped file                      187.3M       32 
shared memory                     1360K       13 
===========                     =======  ======= 
TOTAL                              2.3G     3509 

-----------
Full Report
-----------

{"app_name":"Minesweeper","timestamp":"2024-02-28 10:23:51.00 +0800","app_version":"0.1.0","slice_uuid":"2823d3cc-2b0a-3964-a291-818874629f07","build_version":"1","platform":1,"bundleID":"com.camerongoddard.Minesweeper","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.3.1 (23D60)","roots_installed":0,"name":"Minesweeper","incident_id":"DAE9C84A-125C-49FF-AA98-A3ADFFE3DBFC"}
{
  "uptime" : 70000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,2",
  "coalitionID" : 16540,
  "osVersion" : {
    "train" : "macOS 14.3.1",
    "build" : "23D60",
    "releaseType" : "User"
  },
  "captureTime" : "2024-02-28 10:23:51.4905 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "DAE9C84A-125C-49FF-AA98-A3ADFFE3DBFC",
  "pid" : 68466,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-02-28 10:23:05.9291 +0800",
  "procStartAbsTime" : 1682865385588,
  "procExitAbsTime" : 1683958551982,
  "procName" : "Minesweeper",
  "procPath" : "\/Applications\/Minesweeper.app\/Contents\/MacOS\/Minesweeper",
  "bundleInfo" : {"CFBundleShortVersionString":"0.1.0","CFBundleVersion":"1","CFBundleIdentifier":"com.camerongoddard.Minesweeper"},
  "storeInfo" : {"deviceIdentifierForVendor":"67549C80-E1C0-5A38-9D34-45F3BFED1B08","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.camerongoddard.Minesweeper",
  "crashReporterKey" : "716B7F88-CA2F-82D5-5A3B-B8CC03EDCA93",
  "codeSigningID" : "com.camerongoddard.Minesweeper",
  "codeSigningTeamID" : "AUBXDCV2VL",
  "codeSigningFlags" : 570503953,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"4AMVqv17Ran0T0Sp9ldDqfhfQqn\/gwGRwANf1iAAINTgAxWqutwAlA==","atPC":"IAAg1OEDFapCAYBSJP3\/l\/QDAKr2AwGquf\/\/FyAAINTgAxWqsNwAlA=="},
  "wakeTime" : 5922,
  "sleepWakeUUID" : "C347BB6F-D4BC-4FDE-A415-84F5C93EA231",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000001, 0x00000001027652e4","rawCodes":[1,4336276196],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":68466},
  "os_fault" : {"process":"Minesweeper"},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":52,"task_for_pid":3},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1908315,"threadState":{"x":[{"value":5160877912},{"value":25769803779},{"value":10},{"value":0},{"value":17293822569102704651},{"value":5160877904},{"value":15},{"value":720903},{"value":18446744065119617024},{"value":25769803779},{"value":17179869187},{"value":5160877947},{"value":0},{"value":77},{"value":134217728},{"value":33825},{"value":6753738824,"symbolLocation":0,"symbol":"swift_bridgeObjectRelease"},{"value":3332382257246131672,"symbolLocation":3332382249277456392,"symbol":"full type metadata for String"},{"value":0},{"value":5141237296},{"value":0},{"value":5160877904},{"value":1},{"value":5160721120},{"value":5160721120},{"value":272},{"value":7946153984,"symbolLocation":0,"symbol":"_OBJC_PROTOCOL_REFERENCE_$_NSOpenAndSavePanelRemoteViewExportedToServiceProtocol"},{"value":276},{"value":735576101}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4336275944},"cpsr":{"value":1610616832},"fp":{"value":6130644064},"sp":{"value":6130643984},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4336276196,"matchesCrashFrame":1},"far":{"value":0}},"queue":"com.apple.main-thread","frames":[{"imageOffset":37604,"imageIndex":2},{"imageOffset":30748,"imageIndex":2},{"imageOffset":32388,"imageIndex":2},{"imageOffset":135432,"symbol":"-[SKView rightMouseDown:]","symbolLocation":260,"imageIndex":3},{"imageOffset":11972264,"symbol":"_routeRightMouseDownEvent","symbolLocation":256,"imageIndex":4},{"imageOffset":1463312,"symbol":"-[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]","symbolLocation":400,"imageIndex":4},{"imageOffset":1462444,"symbol":"-[NSWindow(NSEventRouting) sendEvent:]","symbolLocation":284,"imageIndex":4},{"imageOffset":8535904,"symbol":"-[NSApplication(NSEventRouting) sendEvent:]","symbolLocation":1604,"imageIndex":4},{"imageOffset":4670908,"symbol":"-[NSApplication _handleEvent:]","symbolLocation":60,"imageIndex":4},{"imageOffset":185248,"symbol":"-[NSApplication run]","symbolLocation":512,"imageIndex":4},{"imageOffset":17984,"symbol":"NSApplicationMain","symbolLocation":880,"imageIndex":4},{"imageOffset":95784,"imageIndex":2},{"imageOffset":24800,"symbol":"start","symbolLocation":2360,"imageIndex":5}]},{"id":1908329,"name":"CVDisplayLink","threadState":{"x":[{"value":260},{"value":0},{"value":256},{"value":0},{"value":0},{"value":65704},{"value":0},{"value":15626875},{"value":696833},{"value":0},{"value":5167421520},{"value":2},{"value":0},{"value":0},{"value":0},{"value":0},{"value":305},{"value":8092381872},{"value":0},{"value":5167421496},{"value":5167421560},{"value":1},{"value":15626875},{"value":0},{"value":256},{"value":696833},{"value":697088},{"value":7923819024,"symbolLocation":0,"symbol":"CVHostTimeBase::sToNanosDenominator"},{"value":7923820920,"symbolLocation":0,"symbol":"kZeroVideoTime"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6488745512},"cpsr":{"value":2684358656},"fp":{"value":6132919728},"sp":{"value":6132919584},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6488494188},"far":{"value":0}},"frames":[{"imageOffset":20588,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":8},{"imageOffset":30248,"symbol":"_pthread_cond_wait","symbolLocation":1272,"imageIndex":9},{"imageOffset":13608,"symbol":"CVDisplayLink::waitUntil(unsigned long long)","symbolLocation":328,"imageIndex":10},{"imageOffset":9716,"symbol":"CVDisplayLink::runIOThread()","symbolLocation":504,"imageIndex":10},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":9},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":1908336,"name":"com.apple.NSEventThread","threadState":{"x":[{"value":268451845},{"value":21592279046},{"value":8589934592},{"value":272743308197888},{"value":0},{"value":272743308197888},{"value":2},{"value":4294967295},{"value":18446744073709550527},{"value":63503},{"value":0},{"value":1},{"value":63503},{"value":153744},{"value":0},{"value":0},{"value":18446744073709551569},{"value":8092366216},{"value":0},{"value":4294967295},{"value":2},{"value":272743308197888},{"value":0},{"value":272743308197888},{"value":6134063208},{"value":8589934592},{"value":21592279046},{"value":21592279046},{"value":4412409862}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6488554736},"cpsr":{"value":4096},"fp":{"value":6134063056},"sp":{"value":6134062976},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6488479860},"far":{"value":0}},"frames":[{"imageOffset":6260,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":8},{"imageOffset":81136,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":8},{"imageOffset":42160,"symbol":"mach_msg_overwrite","symbolLocation":476,"imageIndex":8},{"imageOffset":7160,"symbol":"mach_msg","symbolLocation":24,"imageIndex":8},{"imageOffset":514948,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":11},{"imageOffset":509004,"symbol":"__CFRunLoopRun","symbolLocation":1208,"imageIndex":11},{"imageOffset":506172,"symbol":"CFRunLoopRunSpecific","symbolLocation":608,"imageIndex":11},{"imageOffset":1454432,"symbol":"_NSEventThread","symbolLocation":144,"imageIndex":4},{"imageOffset":28724,"symbol":"_pthread_start","symbolLocation":136,"imageIndex":9},{"imageOffset":7740,"symbol":"thread_start","symbolLocation":8,"imageIndex":9}]},{"id":1909115,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}],"threadState":{"x":[{"value":6132346880},{"value":55619},{"value":6131810304},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6132346880},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6488722984},"far":{"value":0}}},{"id":1909373,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}],"threadState":{"x":[{"value":6131200000},{"value":51223},{"value":6130663424},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6131200000},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6488722984},"far":{"value":0}}},{"id":1909383,"frames":[{"imageOffset":7720,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":9}],"threadState":{"x":[{"value":6131773440},{"value":50959},{"value":6131236864},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6131773440},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6488722984},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4339744768,
    "size" : 49152,
    "uuid" : "39d1d8d0-6996-3bd4-8ce9-39512bb65c82",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4342120448,
    "CFBundleShortVersionString" : "2.6.0-beta.1",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "80b1ada3-968b-3708-96c5-3994e66106a7",
    "path" : "\/Applications\/Minesweeper.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2034"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4336238592,
    "CFBundleShortVersionString" : "0.1.0",
    "CFBundleIdentifier" : "com.camerongoddard.Minesweeper",
    "size" : 327680,
    "uuid" : "2823d3cc-2b0a-3964-a291-818874629f07",
    "path" : "\/Applications\/Minesweeper.app\/Contents\/MacOS\/Minesweeper",
    "name" : "Minesweeper",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8386740224,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.SpriteKit",
    "size" : 1490944,
    "uuid" : "47d46926-2841-3705-b017-8ebae3987804",
    "path" : "\/System\/Library\/Frameworks\/SpriteKit.framework\/Versions\/A\/SpriteKit",
    "name" : "SpriteKit",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6547992576,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.AppKit",
    "size" : 20103168,
    "uuid" : "873e5da0-bc01-399b-bf60-4066922d6a17",
    "path" : "\/System\/Library\/Frameworks\/AppKit.framework\/Versions\/C\/AppKit",
    "name" : "AppKit",
    "CFBundleVersion" : "2487.40.107"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6485045248,
    "size" : 607112,
    "uuid" : "50746901-db0e-39a0-b391-baaa6b82ad0f",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6749638656,
    "size" : 5509120,
    "uuid" : "7eba7ef0-57d2-3155-b45d-1a4d40a732f3",
    "path" : "\/usr\/lib\/swift\/libswiftCore.dylib",
    "name" : "libswiftCore.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6488473600,
    "size" : 241664,
    "uuid" : "a7228b5d-53c7-3fe9-84e4-2a8c04dcf051",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6488715264,
    "size" : 53236,
    "uuid" : "449bbad3-f7ef-371d-9a59-fd4ffa78289b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6633291776,
    "CFBundleShortVersionString" : "1.8",
    "CFBundleIdentifier" : "com.apple.CoreVideo",
    "size" : 385024,
    "uuid" : "9cd650ce-26fe-3a73-9855-6b3404235ad5",
    "path" : "\/System\/Library\/Frameworks\/CoreVideo.framework\/Versions\/A\/CoreVideo",
    "name" : "CoreVideo",
    "CFBundleVersion" : "604.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6489137152,
    "CFBundleShortVersionString" : "6.9",
    "CFBundleIdentifier" : "com.apple.CoreFoundation",
    "size" : 5079040,
    "uuid" : "6030a572-b731-3f46-b3a0-2598fbb98c9a",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/Versions\/A\/CoreFoundation",
    "name" : "CoreFoundation",
    "CFBundleVersion" : "2303"
  }
],
  "sharedCache" : {
  "base" : 6484295680,
  "size" : 4065345536,
  "uuid" : "c32b200e-cf99-3583-bc9f-b7fb11382e8f"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.6G resident=0K(0%) swapped_out_or_unallocated=1.6G(100%)\nWritable regions: Total=329.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=329.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nAccelerate framework               128K        1 \nActivity Tracing                   256K        1 \nCG image                           112K        4 \nColorSync                          560K       26 \nCoreAnimation                      912K       55 \nCoreGraphics                        48K        3 \nCoreUI image data                  944K        6 \nDispatch continuations            80.0M        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           237.6M       50 \nMALLOC guard page                  192K       12 \nSTACK GUARD                       56.1M        6 \nStack                             10.6M        6 \nVM_ALLOCATE                        208K       13 \n__AUTH                            3072K      423 \n__AUTH_CONST                      33.5M      646 \n__CTF                               824        1 \n__DATA                            17.4M      635 \n__DATA_CONST                      32.8M      654 \n__DATA_DIRTY                      1953K      235 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       892.1M        4 \n__OBJC_RO                         71.2M        1 \n__OBJC_RW                         2171K        1 \n__TEXT                           754.0M      675 \ndyld private memory                272K        2 \nmapped file                      187.3M       32 \nshared memory                     1360K       13 \n===========                     =======  ======= \nTOTAL                              2.3G     3509 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "06b987c1a3ec8dc89fa30936c14c5588c21ff233",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63f9578e238e7b23a1f3030a",
      "factorPackIds" : {

      },
      "deploymentId" : 240000005
    },
    {
      "rolloutId" : "632e379301482c74ed76386c",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_NL" : "6570e25de4d5b2524442a0c1",
        "SIRI_UNDERSTANDING_MORPHUN" : "64e5135c4e666d798a8ffc38",
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "654b1d0e1c6fd434e20893b7"
      },
      "deploymentId" : 240000531
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by cameron-goddard** [comment]
Thanks for pointing this out too! This has also been fixed in a recent commit, and will be released as an update soon.
